// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-books.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-books.ts
var SITE = "https://gyandootnova.in";
var search_books_default = defineTool({
  name: "search_books",
  title: "Search books",
  description: "Search the GyandootNova library of spiritual and devotional books by title, author, description or category.",
  inputSchema: {
    query: z.string().trim().describe("Search text; pass an empty string to list featured books."),
    limit: z.number().int().min(1).max(50).describe("Maximum number of books to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("books").select("title, slug, author, category, description, price, is_free, cover_url").limit(limit);
    if (query) {
      const like = `%${query.replace(/[%,]/g, " ")}%`;
      q = q.or(
        `title.ilike.${like},author.ilike.${like},category.ilike.${like},description.ilike.${like}`
      );
    } else {
      q = q.order("is_featured", { ascending: false }).order("purchase_count", { ascending: false });
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const books = (data ?? []).map((b) => ({ ...b, url: `${SITE}/books/${b.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(books, null, 2) }],
      structuredContent: { books }
    };
  }
});

// src/lib/mcp/tools/get-book.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var SITE2 = "https://gyandootnova.in";
var get_book_default = defineTool2({
  name: "get_book",
  title: "Get book details",
  description: "Fetch full details and the chapter list of one GyandootNova book by its slug (e.g. 'rigved').",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Book slug from its URL, e.g. 'bhagavad-gita'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = supabaseAnon();
    const { data: book, error } = await supabase.from("books").select(
      "id, title, slug, author, category, description, price, is_free, cover_url, preview_chapters, access_validity_days"
    ).eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!book) return { content: [{ type: "text", text: `No book found for slug "${slug}".` }], isError: true };
    const { data: chapters } = await supabase.from("chapters").select("chapter_number, title").eq("book_id", book.id).order("chapter_number", { ascending: true });
    const result = {
      ...book,
      url: `${SITE2}/books/${book.slug}`,
      chapters: chapters ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { book: result }
    };
  }
});

// src/lib/mcp/tools/search-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var SITE3 = "https://gyandootnova.in";
var search_articles_default = defineTool3({
  name: "search_articles",
  title: "Search articles",
  description: "Search published GyandootNova articles and blog posts on Hindu scriptures, meditation and spirituality.",
  inputSchema: {
    query: z3.string().trim().describe("Search text; pass an empty string for the newest articles."),
    limit: z3.number().int().min(1).max(50).describe("Maximum number of articles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("posts").select("title, slug, excerpt, category, published_at, reading_time_min").eq("is_published", true).order("published_at", { ascending: false }).limit(limit);
    if (query) {
      const like = `%${query.replace(/[%,]/g, " ")}%`;
      q = q.or(`title.ilike.${like},excerpt.ilike.${like},category.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const articles = (data ?? []).map((p) => ({ ...p, url: `${SITE3}/articles/${p.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(articles, null, 2) }],
      structuredContent: { articles }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var SITE4 = "https://gyandootnova.in";
var get_article_default = defineTool4({
  name: "get_article",
  title: "Get article",
  description: "Fetch the full text of one published GyandootNova article by its slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Article slug from its URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("posts").select("title, slug, excerpt, content, category, author, published_at, reading_time_min").eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `No published article found for slug "${slug}".` }],
        isError: true
      };
    const article = { ...data, url: `${SITE4}/articles/${data.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(article, null, 2) }],
      structuredContent: { article }
    };
  }
});

// src/lib/mcp/tools/my-library.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var SITE5 = "https://gyandootnova.in";
var my_library_default = defineTool5({
  name: "my_library",
  title: "My library",
  description: "List the books the signed-in GyandootNova user owns, with access validity and purchase details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: purchases, error } = await supabase.rpc("get_user_purchases", {
      _user_id: ctx.getUserId()
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = purchases ?? [];
    const bookIds = rows.map((r) => String(r.book_id)).filter(Boolean);
    let titles = {};
    if (bookIds.length) {
      const { data: books } = await supabase.from("books").select("id, title, slug, author").in("id", bookIds);
      titles = Object.fromEntries(
        (books ?? []).map((b) => [b.id, { title: b.title, slug: b.slug, author: b.author }])
      );
    }
    const library = rows.map((r) => {
      const meta = titles[String(r.book_id)];
      return {
        ...meta,
        url: meta ? `${SITE5}/books/${meta.slug}` : void 0,
        amount: r.amount,
        purchased_at: r.created_at,
        access_validity_days: r.access_validity_days
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(library, null, 2) }],
      structuredContent: { library }
    };
  }
});

// src/lib/mcp/tools/my-reading-progress.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var SITE6 = "https://gyandootnova.in";
var my_reading_progress_default = defineTool6({
  name: "my_reading_progress",
  title: "My reading progress",
  description: "Show where the signed-in GyandootNova user left off in each book they are reading.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("reading_progress").select("book_id, chapter_number, scroll_percent, updated_at").order("updated_at", { ascending: false }).limit(25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    let titles = {};
    if (rows.length) {
      const { data: books } = await supabase.from("books").select("id, title, slug").in("id", rows.map((r) => r.book_id));
      titles = Object.fromEntries((books ?? []).map((b) => [b.id, { title: b.title, slug: b.slug }]));
    }
    const progress = rows.map((r) => {
      const meta = titles[r.book_id];
      return {
        title: meta?.title,
        url: meta ? `${SITE6}/books/${meta.slug}` : void 0,
        chapter_number: r.chapter_number,
        scroll_percent: r.scroll_percent,
        updated_at: r.updated_at
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(progress, null, 2) }],
      structuredContent: { progress }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vrzngahawxtbpwrgxtmb";
var mcp_default = defineMcp({
  name: "gyandootnova",
  title: "GyandootNova",
  version: "0.1.0",
  instructions: "Tools for GyandootNova, a Hindi-first spiritual publication. Use `search_books` and `get_book` to explore the devotional book library, `search_articles` and `get_article` for published articles on scriptures and meditation, and `my_library` / `my_reading_progress` for the signed-in reader's own purchases and reading position.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_books_default, get_book_default, search_articles_default, get_article_default, my_library_default, my_reading_progress_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
